# Generated by Django 3.2.4 on 2021-06-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruityapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruity',
            old_name='description',
            new_name='fruits',
        ),
        migrations.AlterField(
            model_name='fruity',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
