# Generated by Django 3.2.4 on 2021-06-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruityapi', '0002_auto_20210615_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruity',
            old_name='fruits',
            new_name='info',
        ),
        migrations.AlterField(
            model_name='fruity',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
