# Generated by Django 3.2.4 on 2021-06-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruityapi', '0004_alter_fruity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruity',
            name='type',
            field=models.CharField(choices=[('FT', 'Fruit Tea'), ('Y', 'Yakult'), ('MC', 'Milk Cap'), ('M', 'Milk'), ('S', 'Smoothie'), ('MT', 'Milk Tea'), ('SS', 'Signature Smoothie'), ('SD', 'Specialty Drink'), ('FBT', 'Fresh Brewed Tea')], max_length=25),
        ),
    ]
